const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getProjects: () => ipcRenderer.invoke('get-projects'),
  saveProject: (p) => ipcRenderer.invoke('save-project', p),
  deleteProject: (id) => ipcRenderer.invoke('delete-project', id),
  getResources: () => ipcRenderer.invoke('get-resources'),
  saveResource: (r) => ipcRenderer.invoke('save-resource', r),
  deleteResource: (id) => ipcRenderer.invoke('delete-resource', id),
  getNotes: () => ipcRenderer.invoke('get-notes'),
  saveNote: (n) => ipcRenderer.invoke('save-note', n),
  deleteNote: (id) => ipcRenderer.invoke('delete-note', id),
  openFileDialog: () => ipcRenderer.invoke('open-file-dialog'),
  openImageDialog: () => ipcRenderer.invoke('open-image-dialog'),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  openUrl: (url) => ipcRenderer.invoke('open-url-external', url),
  showItemInFolder: (p) => ipcRenderer.invoke('show-item-in-folder', p),
  renameResource: (id, name) => ipcRenderer.invoke('rename-resource', id, name),
  importFile: (src, action) => ipcRenderer.invoke('import-file', src, action),
  getGroups: () => ipcRenderer.invoke('get-groups'),
  saveGroup: (g) => ipcRenderer.invoke('save-group', g),
  deleteGroup: (id) => ipcRenderer.invoke('delete-group', id),
  getResCats: () => ipcRenderer.invoke('get-res-cats'),
  saveResCat: (cat) => ipcRenderer.invoke('save-res-cat', cat),
  deleteResCat: (id) => ipcRenderer.invoke('delete-res-cat', id),
  googleStatus: () => ipcRenderer.invoke('google-status'),
  googleSetCreds: (id, secret) => ipcRenderer.invoke('google-set-creds', id, secret),
  googleConnect: () => ipcRenderer.invoke('google-connect'),
  googleCreateEvent: (event) => ipcRenderer.invoke('google-create-event', event),
  googleDisconnect: () => ipcRenderer.invoke('google-disconnect'),
  onGoogleAuthSuccess: (cb) => ipcRenderer.on('google-auth-success', cb),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  onRemindersChecked: (cb) => ipcRenderer.on('reminders-checked', cb),
  getAppSettings: () => ipcRenderer.invoke('get-app-settings'),
  saveAppSettings: (s) => ipcRenderer.invoke('save-app-settings', s),
  setWindowBackground: (color) => ipcRenderer.invoke('set-window-background', color),
  bulkSaveAll: (data) => ipcRenderer.invoke('bulk-save-all', data),
  serverRequest: (opts) => ipcRenderer.invoke('server-request', opts),
  getWeeklyReviews: () => ipcRenderer.invoke('get-weekly-reviews'),
  saveWeeklyReview: (r) => ipcRenderer.invoke('save-weekly-review', r),
  openProjectWindow: (id) => ipcRenderer.invoke('open-project-window', id),
  onGotoProject: (cb) => ipcRenderer.on('goto-project', (_, id) => cb(id)),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  applyUpdate: () => ipcRenderer.invoke('apply-update'),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (_, msg) => cb(msg)),
  veilleGetCategories: () => ipcRenderer.invoke('veille-get-categories'),
  veilleGetFeeds: () => ipcRenderer.invoke('veille-get-feeds'),
  veilleGetArticles: (opts) => ipcRenderer.invoke('veille-get-articles', opts),
  veilleGetLastRefresh: () => ipcRenderer.invoke('veille-get-last-refresh'),
  veilleSaveCategory: (cat) => ipcRenderer.invoke('veille-save-category', cat),
  veilleDeleteCategory: (id) => ipcRenderer.invoke('veille-delete-category', id),
  veilleSaveFeed: (feed) => ipcRenderer.invoke('veille-save-feed', feed),
  veilleDeleteFeed: (id) => ipcRenderer.invoke('veille-delete-feed', id),
  veilleMarkRead: (ids) => ipcRenderer.invoke('veille-mark-read', ids),
  veilleMarkAllRead: (opts) => ipcRenderer.invoke('veille-mark-all-read', opts),
  veilleRefreshAll: () => ipcRenderer.invoke('veille-refresh-all'),
  veilleTestFeed: (url) => ipcRenderer.invoke('veille-test-feed', url),
  onVeilleRefreshed: (cb) => ipcRenderer.on('veille-refreshed', cb),
});

